AppBundle\Entity\Products:
    type: entity
    table: products
    repositoryClass: AppBundle\Repositories\ProductsRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 128
            fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
        color:
            type: string
            nullable: false
            length: 64
            fixed: false
            default: ''
        size:
            type: string
            nullable: false
            length: 64
            fixed: false
            default: ''
        position:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
        price:
            type: float
            nullable: false
            precision: 2
            scale: 2
            default: '0.00'
    lifecycleCallbacks: {  }
